name: infinite_carousel
description: Carousel in flutter. Supports features like infinite looping, friction effect, multiple scroll physics and control over item anchor and velocity.
version: 1.1.1

homepage: https://github.com/GeekyAnts/infinite-carousel-flutter
repository: https://github.com/GeekyAnts/infinite-carousel-flutter
issue_tracker: https://github.com/GeekyAnts/infinite-carousel-flutter/issues

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

screenshots:

topics:
  - ui
  - carousel
  - widgets
  - infinite
